app:
    datapath: ./data
    description: 开箱即用的文件快传系统
    keywords: FileCodeBox, 文件快递柜, 口令传送箱, 匿名口令分享文本, 文件
    name: FileCodeBox
    production: false
    version: 1.0.0
database:
    db_name: ./data/fileCodeBox.db
    driver: sqlite
download:
    download_timeout: 300
    enable_concurrent_download: true
    max_concurrent_downloads: 10
    require_login: false
log:
    compress: true
    filename: ""
    level: info
    max_age: 30
    max_backups: 10
    max_size: 100
redis:
    db: 0
    host: localhost
    password: ""
    port: 6379
server:
    base_url: http://api.localhost:12345
    host: 0.0.0.0
    mode: debug
    port: 12345
    public_base_url: http://localhost:3000
    read_timeout: 30
    write_timeout: 30
storage:
    qiniu:
        access_key: S7Z0jpuYOSCQeSxF1_oI3I_J8y_sZjFSNUyEiEUi
        bucket: memos1
        domain: cdn.kodo.nmcb.cc
        private: true
        region: z2
        secret_key: e97MfCSsPdYmka3axIauHFekjrlS25VMYCfZW_HH
        use_https: true
    s3:
        access_key_id: ""
        bucket_name: ""
        endpoint_url: ""
        hostname: ""
        proxy: ""
        region_name: us-east-1
        secret_access_key: ""
        signed_url_expiry: 3600
    storage_path: ./data/uploads
    type: upyun
    upyun:
        bucket: kunvideo
        domain: vdo.nmcb.cc
        operator: filebox
        password: ivJawKjfrqqRO9SphEONrNBJITjZm4p3
        secret: 74931f9bfee24dc8b9b9273c35b86eca
ui:
    background: ""
    notify_content: ""
    notify_title: ""
    opacity: 1
    page_explain: 请勿上传或分享违法内容。根据《中华人民共和国网络安全法》、《中华人民共和国刑法》、《中华人民共和国治安管理处罚法》等相关规定。传播或存储违法、违规内容，会受到相关处罚，严重者将承担刑事责任。本站坚决配合相关部门，确保网络内容的安全，和谐，打造绿色网络环境。
    robots_text: |
        User-agent: *
        Disallow: /
    show_admin_addr: false
    theme: themes/2025
upload:
    chunk_size: 5242880
    enable_chunk: true
    max_save_seconds: 0
    open_upload: true
    require_login: false
    share_code_charset: "0123456789"
    share_code_length: 4
    upload_size: 10737418240
user:
    allow_user_registration: false
    jwt_secret: FileCodeBox2025JWT
    max_sessions_per_user: 5
    require_email_verify: false
    session_expiry_hours: 168
    user_storage_quota: 1073741824
    user_upload_size: 52428800
